plugins {
    id 'com.android.application'
}

android {
    namespace 'cz.filip.avsyncmeter'
    compileSdk 35

    defaultConfig {
        applicationId 'cz.filip.avsyncmeter'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '0.1.3'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
