from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import pandas as pd


@dataclass(frozen=True, slots=True)
class FieldSpec:
    path: str
    alias: str
    optional: bool = False


@dataclass(frozen=True, slots=True)
class ReportDefinition:
    key: str
    sheet_name: str
    query_file: str | None
    fields: tuple[FieldSpec, ...]
    priority: bool = False

    @property
    def aliases(self) -> list[str]:
        return [field.alias for field in self.fields]

    @property
    def required_fields(self) -> tuple[FieldSpec, ...]:
        return tuple(field for field in self.fields if not field.optional)

    @property
    def optional_aliases(self) -> list[str]:
        return [field.alias for field in self.fields if field.optional]

    def query_path(self, project_root: Path) -> Path:
        if self.query_file is None:
            raise ValueError(f"Report {self.key} is synthetic and has no query file.")
        return project_root / "app" / "google_ads" / "queries" / self.query_file

    @property
    def supports_fetch(self) -> bool:
        return self.query_file is not None


def _common_perf_fields() -> tuple[FieldSpec, ...]:
    return (
        FieldSpec("metrics.impressions", "impressions"),
        FieldSpec("metrics.clicks", "clicks"),
        FieldSpec("metrics.cost_micros", "cost_micros"),
        FieldSpec("metrics.average_cpc", "average_cpc"),
        FieldSpec("metrics.ctr", "ctr"),
        FieldSpec("metrics.conversions", "conversions"),
        FieldSpec("metrics.cost_per_conversion", "cost_per_conversion"),
        FieldSpec("metrics.conversions_from_interactions_rate", "conversion_rate"),
        FieldSpec("metrics.conversions_value", "conversions_value"),
        FieldSpec("metrics.value_per_conversion", "value_per_conversion"),
    )


REPORTS: dict[str, ReportDefinition] = {
    "account": ReportDefinition(
        key="account",
        sheet_name="Account",
        query_file="account.sql",
        fields=(
            FieldSpec("customer.id", "customer_id"),
            FieldSpec("customer.descriptive_name", "descriptive_name"),
            FieldSpec("customer.currency_code", "currency_code"),
            FieldSpec("customer.time_zone", "time_zone"),
            FieldSpec("customer.tracking_url_template", "tracking_url_template", optional=True),
            FieldSpec("customer.final_url_suffix", "final_url_suffix", optional=True),
            FieldSpec("customer.auto_tagging_enabled", "auto_tagging_enabled", optional=True),
        ),
    ),
    "account_diagnostics": ReportDefinition(
        key="account_diagnostics",
        sheet_name="Account diagnostics",
        query_file=None,
        fields=(
            FieldSpec("diagnostic_key", "diagnostic_key"),
            FieldSpec("label", "label"),
            FieldSpec("value", "value"),
            FieldSpec("status", "status"),
            FieldSpec("details", "details"),
        ),
    ),
    "linked_accounts": ReportDefinition(
        key="linked_accounts",
        sheet_name="Linked accounts",
        query_file=None,
        fields=(
            FieldSpec("service_key", "service_key"),
            FieldSpec("service_name", "service_name"),
            FieldSpec("status", "status"),
            FieldSpec("linked_account_id", "linked_account_id"),
            FieldSpec("linked_account_name", "linked_account_name"),
            FieldSpec("evidence_source", "evidence_source"),
            FieldSpec("details", "details"),
        ),
    ),
    "campaigns": ReportDefinition(
        key="campaigns",
        sheet_name="Campaigns",
        query_file="campaigns.sql",
        fields=(
            FieldSpec("campaign.id", "campaign_id"),
            FieldSpec("campaign.name", "campaign_name"),
            FieldSpec("campaign.status", "campaign_status"),
            FieldSpec("campaign.advertising_channel_type", "advertising_channel_type"),
            FieldSpec("campaign.advertising_channel_sub_type", "advertising_channel_sub_type", optional=True),
            FieldSpec("campaign.bidding_strategy_type", "bidding_strategy_type"),
            FieldSpec("campaign_budget.name", "campaign_budget", optional=True),
            FieldSpec("campaign_budget.amount_micros", "budget_amount_micros", optional=True),
            FieldSpec("campaign.optimization_score", "optimization_score", optional=True),
            *_common_perf_fields(),
            FieldSpec("metrics.all_conversions", "all_conversions"),
            FieldSpec("metrics.all_conversions_value", "all_conversions_value"),
            FieldSpec("metrics.search_impression_share", "search_impression_share", optional=True),
            FieldSpec(
                "metrics.search_budget_lost_impression_share",
                "search_budget_lost_impression_share",
                optional=True,
            ),
            FieldSpec(
                "metrics.search_rank_lost_impression_share",
                "search_rank_lost_impression_share",
                optional=True,
            ),
        ),
    ),
    "ad_groups": ReportDefinition(
        key="ad_groups",
        sheet_name="Ad groups",
        query_file="ad_groups.sql",
        fields=(
            FieldSpec("campaign.id", "campaign_id"),
            FieldSpec("campaign.name", "campaign_name"),
            FieldSpec("ad_group.id", "ad_group_id"),
            FieldSpec("ad_group.name", "ad_group_name"),
            FieldSpec("ad_group.status", "ad_group_status"),
            FieldSpec("ad_group.type", "ad_group_type", optional=True),
            *_common_perf_fields(),
        ),
    ),
    "keywords": ReportDefinition(
        key="keywords",
        sheet_name="Keywords",
        query_file="keywords.sql",
        fields=(
            FieldSpec("campaign.id", "campaign_id"),
            FieldSpec("campaign.name", "campaign_name"),
            FieldSpec("ad_group.id", "ad_group_id"),
            FieldSpec("ad_group.name", "ad_group_name"),
            FieldSpec("ad_group_criterion.criterion_id", "criterion_id"),
            FieldSpec("ad_group_criterion.keyword.text", "keyword_text"),
            FieldSpec("ad_group_criterion.keyword.match_type", "keyword_match_type"),
            FieldSpec("ad_group_criterion.status", "keyword_status"),
            FieldSpec("ad_group_criterion.quality_info.quality_score", "quality_score", optional=True),
            FieldSpec(
                "ad_group_criterion.quality_info.creative_quality_score",
                "creative_quality_score",
                optional=True,
            ),
            FieldSpec(
                "ad_group_criterion.quality_info.post_click_quality_score",
                "post_click_quality_score",
                optional=True,
            ),
            FieldSpec(
                "ad_group_criterion.quality_info.search_predicted_ctr",
                "search_predicted_ctr",
                optional=True,
            ),
            *_common_perf_fields(),
        ),
    ),
    "search_terms": ReportDefinition(
        key="search_terms",
        sheet_name="Search terms",
        query_file="search_terms.sql",
        priority=True,
        fields=(
            FieldSpec("campaign.id", "campaign_id"),
            FieldSpec("campaign.name", "campaign_name"),
            FieldSpec("ad_group.id", "ad_group_id"),
            FieldSpec("ad_group.name", "ad_group_name"),
            FieldSpec("search_term_view.search_term", "search_term"),
            FieldSpec("segments.keyword.info.text", "keyword_text", optional=True),
            FieldSpec("segments.keyword.info.match_type", "keyword_match_type", optional=True),
            *_common_perf_fields(),
        ),
    ),
    "ads": ReportDefinition(
        key="ads",
        sheet_name="Ads",
        query_file="ads.sql",
        fields=(
            FieldSpec("campaign.id", "campaign_id"),
            FieldSpec("campaign.name", "campaign_name"),
            FieldSpec("ad_group.id", "ad_group_id"),
            FieldSpec("ad_group.name", "ad_group_name"),
            FieldSpec("ad_group_ad.ad.id", "ad_id"),
            FieldSpec("ad_group_ad.status", "ad_group_ad_status"),
            FieldSpec("ad_group_ad.ad.type", "ad_type"),
            FieldSpec("ad_group_ad.ad_strength", "ad_strength", optional=True),
            FieldSpec("ad_group_ad.ad.final_urls", "final_urls", optional=True),
            FieldSpec(
                "ad_group_ad.ad.responsive_search_ad.headlines",
                "responsive_search_ad_headlines",
                optional=True,
            ),
            FieldSpec(
                "ad_group_ad.ad.responsive_search_ad.descriptions",
                "responsive_search_ad_descriptions",
                optional=True,
            ),
            *_common_perf_fields(),
        ),
    ),
    "assets": ReportDefinition(
        key="assets",
        sheet_name="Assets",
        query_file="assets.sql",
        fields=(
            FieldSpec("campaign.id", "campaign_id", optional=True),
            FieldSpec("campaign.name", "campaign_name", optional=True),
            FieldSpec("asset.id", "asset_id"),
            FieldSpec("asset.name", "asset_name", optional=True),
            FieldSpec("asset.type", "asset_type"),
            FieldSpec("ad_group_ad_asset_view.field_type", "field_type", optional=True),
            FieldSpec("asset.source", "source", optional=True),
            FieldSpec("ad_group_ad_asset_view.performance_label", "performance_label", optional=True),
            FieldSpec("asset.text_asset.text", "text_asset_text", optional=True),
            FieldSpec("asset.sitelink_asset.link_text", "sitelink_text", optional=True),
            FieldSpec("asset.callout_asset.callout_text", "callout_text", optional=True),
            FieldSpec("metrics.impressions", "impressions"),
            FieldSpec("metrics.clicks", "clicks"),
            FieldSpec("metrics.cost_micros", "cost_micros"),
            FieldSpec("metrics.ctr", "ctr"),
            FieldSpec("metrics.conversions", "conversions"),
            FieldSpec("metrics.conversions_value", "conversions_value"),
        ),
    ),
    "devices": ReportDefinition(
        key="devices",
        sheet_name="Devices",
        query_file="devices.sql",
        fields=(
            FieldSpec("campaign.id", "campaign_id"),
            FieldSpec("campaign.name", "campaign_name"),
            FieldSpec("segments.device", "device"),
            *_common_perf_fields(),
        ),
    ),
    "locations": ReportDefinition(
        key="locations",
        sheet_name="Locations",
        query_file="locations.sql",
        fields=(
            FieldSpec("campaign.id", "campaign_id"),
            FieldSpec("campaign.name", "campaign_name"),
            FieldSpec("geographic_view.country_criterion_id", "country_criterion_id"),
            FieldSpec("geographic_view.location_type", "location_type"),
            FieldSpec("segments.geo_target_most_specific_location", "geo_target_name", optional=True),
            *_common_perf_fields(),
        ),
    ),
    "landing_pages": ReportDefinition(
        key="landing_pages",
        sheet_name="Landing pages",
        query_file="landing_pages.sql",
        fields=(
            FieldSpec("expanded_landing_page_view.expanded_final_url", "expanded_final_url"),
            FieldSpec("campaign.id", "campaign_id", optional=True),
            FieldSpec("campaign.name", "campaign_name", optional=True),
            FieldSpec("ad_group.id", "ad_group_id", optional=True),
            FieldSpec("ad_group.name", "ad_group_name", optional=True),
            *_common_perf_fields(),
        ),
    ),
    "shopping_products": ReportDefinition(
        key="shopping_products",
        sheet_name="Shopping products",
        query_file="shopping_products.sql",
        fields=(
            FieldSpec("campaign.id", "campaign_id"),
            FieldSpec("campaign.name", "campaign_name"),
            FieldSpec("ad_group.id", "ad_group_id", optional=True),
            FieldSpec("ad_group.name", "ad_group_name", optional=True),
            FieldSpec("segments.product_item_id", "product_item_id"),
            FieldSpec("segments.product_title", "product_title", optional=True),
            FieldSpec("segments.product_brand", "product_brand", optional=True),
            FieldSpec("segments.product_category_level1", "product_category_level1", optional=True),
            FieldSpec("segments.product_category_level2", "product_category_level2", optional=True),
            FieldSpec("segments.product_category_level3", "product_category_level3", optional=True),
            FieldSpec("segments.product_type_l1", "product_type_l1", optional=True),
            FieldSpec("segments.product_type_l2", "product_type_l2", optional=True),
            FieldSpec("segments.product_type_l3", "product_type_l3", optional=True),
            FieldSpec("segments.product_custom_attribute0", "custom_label_0", optional=True),
            FieldSpec("segments.product_custom_attribute1", "custom_label_1", optional=True),
            FieldSpec("segments.product_custom_attribute2", "custom_label_2", optional=True),
            FieldSpec("segments.product_custom_attribute3", "custom_label_3", optional=True),
            FieldSpec("segments.product_custom_attribute4", "custom_label_4", optional=True),
            *_common_perf_fields(),
            FieldSpec("metrics.all_conversions", "all_conversions"),
            FieldSpec("metrics.all_conversions_value", "all_conversions_value"),
        ),
    ),
    "shopping_products_summary": ReportDefinition(
        key="shopping_products_summary",
        sheet_name="Shopping products summary",
        query_file=None,
        fields=(
            FieldSpec("product_item_id", "product_item_id"),
            FieldSpec("product_title", "product_title"),
            FieldSpec("product_brand", "product_brand"),
            FieldSpec("custom_label_0", "custom_label_0"),
            FieldSpec("custom_label_1", "custom_label_1"),
            FieldSpec("custom_label_2", "custom_label_2"),
            FieldSpec("custom_label_3", "custom_label_3"),
            FieldSpec("custom_label_4", "custom_label_4"),
            FieldSpec("impressions", "impressions"),
            FieldSpec("clicks", "clicks"),
            FieldSpec("cost_micros", "cost_micros"),
            FieldSpec("conversions", "conversions"),
            FieldSpec("conversions_value", "conversions_value"),
            FieldSpec("all_conversions", "all_conversions"),
            FieldSpec("all_conversions_value", "all_conversions_value"),
            FieldSpec("average_cpc", "average_cpc"),
            FieldSpec("conversion_rate", "conversion_rate"),
            FieldSpec("cost_per_conversion", "cost_per_conversion"),
            FieldSpec("value_per_conversion", "value_per_conversion"),
            FieldSpec("row_count", "row_count"),
        ),
    ),
    "merchant_products": ReportDefinition(
        key="merchant_products",
        sheet_name="Merchant products",
        query_file=None,
        fields=(
            FieldSpec("merchant_account_id", "merchant_account_id"),
            FieldSpec("offer_id", "offer_id"),
            FieldSpec("item_id", "item_id"),
            FieldSpec("title", "title"),
            FieldSpec("description", "description"),
            FieldSpec("brand", "brand"),
            FieldSpec("gtin", "gtin"),
            FieldSpec("mpn", "mpn"),
            FieldSpec("link", "link"),
            FieldSpec("image_link", "image_link"),
            FieldSpec("price", "price"),
            FieldSpec("sale_price", "sale_price"),
            FieldSpec("availability", "availability"),
            FieldSpec("condition", "condition"),
            FieldSpec("google_product_category", "google_product_category"),
            FieldSpec("product_type", "product_type"),
            FieldSpec("custom_label_0", "custom_label_0"),
            FieldSpec("custom_label_1", "custom_label_1"),
            FieldSpec("custom_label_2", "custom_label_2"),
            FieldSpec("custom_label_3", "custom_label_3"),
            FieldSpec("custom_label_4", "custom_label_4"),
            FieldSpec("channel", "channel"),
            FieldSpec("content_language", "content_language"),
            FieldSpec("target_country", "target_country"),
            FieldSpec("feed_label", "feed_label"),
            FieldSpec("last_update_time", "last_update_time"),
        ),
    ),
    "merchant_product_issues": ReportDefinition(
        key="merchant_product_issues",
        sheet_name="Merchant product issues",
        query_file=None,
        fields=(
            FieldSpec("merchant_account_id", "merchant_account_id"),
            FieldSpec("item_id", "item_id"),
            FieldSpec("title", "title"),
            FieldSpec("destination", "destination"),
            FieldSpec("country", "country"),
            FieldSpec("issue_code", "issue_code"),
            FieldSpec("issue_severity", "issue_severity"),
            FieldSpec("issue_title", "issue_title"),
            FieldSpec("issue_description", "issue_description"),
            FieldSpec("documentation_link", "documentation_link"),
            FieldSpec("affected_destination", "affected_destination"),
            FieldSpec("status", "status"),
            FieldSpec("cost_micros", "cost_micros"),
            FieldSpec("clicks", "clicks"),
            FieldSpec("conversions", "conversions"),
            FieldSpec("conversions_value", "conversions_value"),
        ),
    ),
    "merchant_product_status_summary": ReportDefinition(
        key="merchant_product_status_summary",
        sheet_name="Merchant product status summary",
        query_file=None,
        fields=(
            FieldSpec("merchant_account_id", "merchant_account_id"),
            FieldSpec("reporting_context", "reporting_context"),
            FieldSpec("country", "country"),
            FieldSpec("approved", "approved"),
            FieldSpec("pending", "pending"),
            FieldSpec("disapproved", "disapproved"),
            FieldSpec("expiring", "expiring"),
        ),
    ),
    "product_optimization": ReportDefinition(
        key="product_optimization",
        sheet_name="Product optimization",
        query_file=None,
        fields=(
            FieldSpec("entity_type", "entity_type"),
            FieldSpec("entity_id", "entity_id"),
            FieldSpec("entity_name", "entity_name"),
            FieldSpec("parent_campaign", "parent_campaign"),
            FieldSpec("flag_type", "flag_type"),
            FieldSpec("severity", "severity"),
            FieldSpec("metric_1", "metric_1"),
            FieldSpec("metric_2", "metric_2"),
            FieldSpec("note", "note"),
        ),
    ),
    "product_feed_issues_with_spend": ReportDefinition(
        key="product_feed_issues_with_spend",
        sheet_name="Product feed issues with spend",
        query_file=None,
        fields=(
            FieldSpec("item_id", "item_id"),
            FieldSpec("title", "title"),
            FieldSpec("issue_code", "issue_code"),
            FieldSpec("issue_severity", "issue_severity"),
            FieldSpec("status", "status"),
            FieldSpec("cost_micros", "cost_micros"),
            FieldSpec("clicks", "clicks"),
            FieldSpec("conversions", "conversions"),
            FieldSpec("conversions_value", "conversions_value"),
            FieldSpec("custom_label_0", "custom_label_0"),
            FieldSpec("custom_label_1", "custom_label_1"),
            FieldSpec("custom_label_2", "custom_label_2"),
            FieldSpec("custom_label_3", "custom_label_3"),
            FieldSpec("custom_label_4", "custom_label_4"),
            FieldSpec("note", "note"),
        ),
    ),
    "product_custom_label_performance": ReportDefinition(
        key="product_custom_label_performance",
        sheet_name="Product custom label perf",
        query_file=None,
        fields=(
            FieldSpec("label_name", "label_name"),
            FieldSpec("label_value", "label_value"),
            FieldSpec("item_count", "item_count"),
            FieldSpec("impressions", "impressions"),
            FieldSpec("clicks", "clicks"),
            FieldSpec("cost_micros", "cost_micros"),
            FieldSpec("conversions", "conversions"),
            FieldSpec("conversions_value", "conversions_value"),
            FieldSpec("average_cpc", "average_cpc"),
            FieldSpec("conversion_rate", "conversion_rate"),
            FieldSpec("cost_per_conversion", "cost_per_conversion"),
            FieldSpec("value_per_conversion", "value_per_conversion"),
            FieldSpec("roas", "roas"),
        ),
    ),
    "ga4_landing_pages": ReportDefinition(
        key="ga4_landing_pages",
        sheet_name="GA4 landing pages",
        query_file=None,
        fields=(
            FieldSpec("landing_page", "landing_page"),
            FieldSpec("session_source_medium", "session_source_medium"),
            FieldSpec("session_campaign_name", "session_campaign_name"),
            FieldSpec("device_category", "device_category"),
            FieldSpec("country", "country"),
            FieldSpec("sessions", "sessions"),
            FieldSpec("engaged_sessions", "engaged_sessions"),
            FieldSpec("engagement_rate", "engagement_rate"),
            FieldSpec("average_session_duration", "average_session_duration"),
            FieldSpec("event_count", "event_count"),
            FieldSpec("key_events", "key_events"),
            FieldSpec("total_revenue", "total_revenue"),
            FieldSpec("transactions", "transactions"),
        ),
    ),
    "landing_page_diagnostics": ReportDefinition(
        key="landing_page_diagnostics",
        sheet_name="Landing page diagnostics",
        query_file=None,
        fields=(
            FieldSpec("landing_page_url", "landing_page_url"),
            FieldSpec("landing_page_path", "landing_page_path"),
            FieldSpec("campaign_name", "campaign_name"),
            FieldSpec("cost_micros", "cost_micros"),
            FieldSpec("clicks", "clicks"),
            FieldSpec("conversions", "conversions"),
            FieldSpec("conversions_value", "conversions_value"),
            FieldSpec("sessions", "sessions"),
            FieldSpec("engaged_sessions", "engaged_sessions"),
            FieldSpec("engagement_rate", "engagement_rate"),
            FieldSpec("average_session_duration", "average_session_duration"),
            FieldSpec("transactions", "transactions"),
            FieldSpec("total_revenue", "total_revenue"),
            FieldSpec("diagnosis", "diagnosis"),
            FieldSpec("severity", "severity"),
            FieldSpec("note", "note"),
        ),
    ),
    "ga4_ecommerce_funnel": ReportDefinition(
        key="ga4_ecommerce_funnel",
        sheet_name="GA4 ecommerce funnel",
        query_file=None,
        fields=(
            FieldSpec("breakdown_type", "breakdown_type"),
            FieldSpec("parent_campaign", "parent_campaign"),
            FieldSpec("breakdown_value", "breakdown_value"),
            FieldSpec("breakdown_label", "breakdown_label"),
            FieldSpec("secondary_value", "secondary_value"),
            FieldSpec("view_item_count", "view_item_count"),
            FieldSpec("add_to_cart_count", "add_to_cart_count"),
            FieldSpec("begin_checkout_count", "begin_checkout_count"),
            FieldSpec("purchase_count", "purchase_count"),
            FieldSpec("dropoff_after_view_item", "dropoff_after_view_item"),
            FieldSpec("dropoff_after_add_to_cart", "dropoff_after_add_to_cart"),
            FieldSpec("dropoff_after_begin_checkout", "dropoff_after_begin_checkout"),
            FieldSpec("purchase_rate_from_view_item", "purchase_rate_from_view_item"),
            FieldSpec("total_revenue", "total_revenue"),
            FieldSpec("transactions", "transactions"),
            FieldSpec("diagnosis", "diagnosis"),
        ),
    ),
    "gsc_queries": ReportDefinition(
        key="gsc_queries",
        sheet_name="GSC queries",
        query_file=None,
        fields=(
            FieldSpec("date", "date"),
            FieldSpec("query", "query"),
            FieldSpec("page", "page"),
            FieldSpec("country", "country"),
            FieldSpec("device", "device"),
            FieldSpec("clicks", "clicks"),
            FieldSpec("impressions", "impressions"),
            FieldSpec("ctr", "ctr"),
            FieldSpec("position", "position"),
        ),
    ),
    "gsc_pages": ReportDefinition(
        key="gsc_pages",
        sheet_name="GSC pages",
        query_file=None,
        fields=(
            FieldSpec("date", "date"),
            FieldSpec("page", "page"),
            FieldSpec("country", "country"),
            FieldSpec("device", "device"),
            FieldSpec("clicks", "clicks"),
            FieldSpec("impressions", "impressions"),
            FieldSpec("ctr", "ctr"),
            FieldSpec("position", "position"),
        ),
    ),
    "gsc_page_query": ReportDefinition(
        key="gsc_page_query",
        sheet_name="GSC page-query",
        query_file=None,
        fields=(
            FieldSpec("date", "date"),
            FieldSpec("query", "query"),
            FieldSpec("page", "page"),
            FieldSpec("country", "country"),
            FieldSpec("device", "device"),
            FieldSpec("clicks", "clicks"),
            FieldSpec("impressions", "impressions"),
            FieldSpec("ctr", "ctr"),
            FieldSpec("position", "position"),
        ),
    ),
    "gsc_opportunities": ReportDefinition(
        key="gsc_opportunities",
        sheet_name="GSC opportunities",
        query_file=None,
        fields=(
            FieldSpec("entity_type", "entity_type"),
            FieldSpec("entity_id", "entity_id"),
            FieldSpec("entity_name", "entity_name"),
            FieldSpec("parent_page", "parent_page"),
            FieldSpec("flag_type", "flag_type"),
            FieldSpec("severity", "severity"),
            FieldSpec("metric_1", "metric_1"),
            FieldSpec("metric_2", "metric_2"),
            FieldSpec("note", "note"),
        ),
    ),
    "pagespeed_landing_pages": ReportDefinition(
        key="pagespeed_landing_pages",
        sheet_name="PageSpeed landing pages",
        query_file=None,
        fields=(
            FieldSpec("url", "url"),
            FieldSpec("strategy", "strategy"),
            FieldSpec("performance_score", "performance_score"),
            FieldSpec("accessibility_score", "accessibility_score"),
            FieldSpec("seo_score", "seo_score"),
            FieldSpec("best_practices_score", "best_practices_score"),
            FieldSpec("lcp", "lcp"),
            FieldSpec("cls", "cls"),
            FieldSpec("inp", "inp"),
            FieldSpec("fcp", "fcp"),
            FieldSpec("speed_index", "speed_index"),
            FieldSpec("diagnostics_json", "diagnostics_json"),
            FieldSpec("opportunities_json", "opportunities_json"),
        ),
    ),
    "gtm_tags": ReportDefinition(
        key="gtm_tags",
        sheet_name="GTM tags",
        query_file=None,
        fields=(
            FieldSpec("workspace_id", "workspace_id"),
            FieldSpec("workspace_name", "workspace_name"),
            FieldSpec("tag_id", "tag_id"),
            FieldSpec("name", "name"),
            FieldSpec("type", "type"),
            FieldSpec("live_only", "live_only"),
            FieldSpec("firing_trigger_ids", "firing_trigger_ids"),
            FieldSpec("blocking_trigger_ids", "blocking_trigger_ids"),
            FieldSpec("consent_settings", "consent_settings"),
            FieldSpec("schedule_start_ms", "schedule_start_ms"),
            FieldSpec("schedule_end_ms", "schedule_end_ms"),
            FieldSpec("notes", "notes"),
            FieldSpec("parameter_json", "parameter_json"),
        ),
    ),
    "gtm_triggers": ReportDefinition(
        key="gtm_triggers",
        sheet_name="GTM triggers",
        query_file=None,
        fields=(
            FieldSpec("workspace_id", "workspace_id"),
            FieldSpec("workspace_name", "workspace_name"),
            FieldSpec("trigger_id", "trigger_id"),
            FieldSpec("name", "name"),
            FieldSpec("type", "type"),
            FieldSpec("event_name", "event_name"),
            FieldSpec("filter_json", "filter_json"),
            FieldSpec("parameter_json", "parameter_json"),
        ),
    ),
    "gtm_variables": ReportDefinition(
        key="gtm_variables",
        sheet_name="GTM variables",
        query_file=None,
        fields=(
            FieldSpec("workspace_id", "workspace_id"),
            FieldSpec("workspace_name", "workspace_name"),
            FieldSpec("variable_id", "variable_id"),
            FieldSpec("name", "name"),
            FieldSpec("type", "type"),
            FieldSpec("notes", "notes"),
            FieldSpec("parameter_json", "parameter_json"),
        ),
    ),
    "gtm_versions": ReportDefinition(
        key="gtm_versions",
        sheet_name="GTM versions",
        query_file=None,
        fields=(
            FieldSpec("container_version_id", "container_version_id"),
            FieldSpec("name", "name"),
            FieldSpec("deleted", "deleted"),
            FieldSpec("num_tags", "num_tags"),
            FieldSpec("num_triggers", "num_triggers"),
            FieldSpec("num_variables", "num_variables"),
            FieldSpec("notes", "notes"),
        ),
    ),
    "measurement_diagnostics": ReportDefinition(
        key="measurement_diagnostics",
        sheet_name="Measurement diagnostics",
        query_file=None,
        fields=(
            FieldSpec("diagnostic_key", "diagnostic_key"),
            FieldSpec("label", "label"),
            FieldSpec("value", "value"),
            FieldSpec("status", "status"),
            FieldSpec("details", "details"),
        ),
    ),
    "google_ads_recommendations": ReportDefinition(
        key="google_ads_recommendations",
        sheet_name="Google Ads recommendations",
        query_file="google_ads_recommendations.sql",
        fields=(
            FieldSpec("recommendation.resource_name", "recommendation_resource_name"),
            FieldSpec("campaign.id", "campaign_id", optional=True),
            FieldSpec("campaign.name", "campaign_name", optional=True),
            FieldSpec("recommendation.campaign", "campaign_resource_name", optional=True),
            FieldSpec("recommendation.type", "recommendation_type"),
            FieldSpec("recommendation.dismissed", "dismissed", optional=True),
        ),
    ),
    "conversion_actions": ReportDefinition(
        key="conversion_actions",
        sheet_name="Conversions",
        query_file="conversion_actions.sql",
        fields=(
            FieldSpec("conversion_action.id", "conversion_action_id"),
            FieldSpec("conversion_action.name", "conversion_action_name"),
            FieldSpec("conversion_action.status", "status"),
            FieldSpec("conversion_action.type", "type"),
            FieldSpec("conversion_action.category", "category"),
            FieldSpec("conversion_action.primary_for_goal", "primary_for_goal"),
            FieldSpec("conversion_action.include_in_conversions_metric", "include_in_conversions_metric"),
            FieldSpec(
                "conversion_action.value_settings.default_value",
                "default_value",
                optional=True,
            ),
            FieldSpec(
                "conversion_action.value_settings.default_currency_code",
                "default_currency_code",
                optional=True,
            ),
            FieldSpec(
                "conversion_action.value_settings.always_use_default_value",
                "always_use_default_value",
                optional=True,
            ),
            FieldSpec("conversion_action.counting_type", "counting_type", optional=True),
            FieldSpec(
                "conversion_action.attribution_model_settings.attribution_model",
                "attribution_model",
                optional=True,
            ),
            FieldSpec(
                "conversion_action.attribution_model_settings.data_driven_model_status",
                "data_driven_model_status",
                optional=True,
            ),
        ),
    ),
    "pmax_campaigns": ReportDefinition(
        key="pmax_campaigns",
        sheet_name="PMax campaigns",
        query_file="pmax_campaigns.sql",
        fields=(
            FieldSpec("campaign.id", "campaign_id"),
            FieldSpec("campaign.name", "campaign_name"),
            FieldSpec("campaign.status", "campaign_status"),
            FieldSpec("campaign.advertising_channel_type", "advertising_channel_type"),
            FieldSpec("campaign.advertising_channel_sub_type", "advertising_channel_sub_type", optional=True),
            FieldSpec("campaign.bidding_strategy_type", "bidding_strategy_type"),
            *_common_perf_fields(),
        ),
    ),
    "pmax_asset_groups": ReportDefinition(
        key="pmax_asset_groups",
        sheet_name="PMax asset groups",
        query_file="pmax_asset_groups.sql",
        fields=(
            FieldSpec("campaign.id", "campaign_id"),
            FieldSpec("campaign.name", "campaign_name"),
            FieldSpec("asset_group.id", "asset_group_id"),
            FieldSpec("asset_group.name", "asset_group_name"),
            FieldSpec("asset_group.status", "asset_group_status"),
            FieldSpec("metrics.impressions", "impressions"),
            FieldSpec("metrics.clicks", "clicks"),
            FieldSpec("metrics.cost_micros", "cost_micros"),
            FieldSpec("metrics.ctr", "ctr"),
            FieldSpec("metrics.conversions", "conversions"),
            FieldSpec("metrics.cost_per_conversion", "cost_per_conversion"),
            FieldSpec("metrics.conversions_value", "conversions_value"),
            FieldSpec("metrics.value_per_conversion", "value_per_conversion"),
        ),
    ),
    "change_history": ReportDefinition(
        key="change_history",
        sheet_name="Change history",
        query_file="change_history.sql",
        fields=(
            FieldSpec("change_event.change_date_time", "change_date_time"),
            FieldSpec("change_event.user_email", "user_email", optional=True),
            FieldSpec("change_event.resource_change_operation", "resource_type"),
            FieldSpec("change_event.resource_name", "resource_name"),
            FieldSpec("change_event.client_type", "client_type"),
            FieldSpec("change_event.change_resource_type", "change_resource_type"),
            FieldSpec("change_event.changed_fields", "changed_fields", optional=True),
            FieldSpec("change_event.old_resource", "old_resource", optional=True),
            FieldSpec("change_event.new_resource", "new_resource", optional=True),
        ),
    ),
}


REPORTS["campaigns_monthly"] = ReportDefinition(
    key="campaigns_monthly",
    sheet_name="Campaigns monthly",
    query_file="campaigns_monthly.sql",
    fields=(FieldSpec("segments.month", "month"), *REPORTS["campaigns"].fields),
)

REPORT_ORDER = [
    "account",
    "account_diagnostics",
    "linked_accounts",
    "campaigns",
    "campaigns_monthly",
    "ad_groups",
    "keywords",
    "search_terms",
    "ads",
    "assets",
    "devices",
    "locations",
    "landing_pages",
    "shopping_products",
    "shopping_products_summary",
    "merchant_products",
    "merchant_product_issues",
    "merchant_product_status_summary",
    "product_optimization",
    "product_feed_issues_with_spend",
    "product_custom_label_performance",
    "ga4_landing_pages",
    "landing_page_diagnostics",
    "ga4_ecommerce_funnel",
    "gsc_queries",
    "gsc_pages",
    "gsc_page_query",
    "gsc_opportunities",
    "pagespeed_landing_pages",
    "gtm_tags",
    "gtm_triggers",
    "gtm_variables",
    "gtm_versions",
    "measurement_diagnostics",
    "google_ads_recommendations",
    "conversion_actions",
    "pmax_campaigns",
    "pmax_asset_groups",
    "change_history",
]


def get_report_definition(report_key: str) -> ReportDefinition:
    return REPORTS[report_key]


def empty_report_frame(report: ReportDefinition) -> pd.DataFrame:
    return pd.DataFrame(columns=report.aliases)


def report_aliases(report_keys: Iterable[str]) -> dict[str, list[str]]:
    return {key: REPORTS[key].aliases for key in report_keys}
