version: 2
saved_at: '2026-02-17T09:13:09.876556+00:00'
source_file: smartemailing_api
source_kind: smartemailing_api
schema_hash: 77ab2b62daa787adc2f05e913265f43206ef6b54b8b1f1e6becbfb37ccb509d2
columns:
- E-mail
- Společnost
- Město
- Země
- okres
- Tituly před jménem
- Jméno
- Příjmení
- Tituly za jménem
- Poznámky
- prohlížené aplikace plusSystem
- Souhlas se zpracováním
- id - integromat
- Čas návštěvy - integromat
- Teritorium - integromat
- IČ - integromat
- Region - integromat
- Země - integromat
- Typ subjektu - integromat
- Hlavní obor - integromat
- Obrat - integromat
- Zaměstnanců - integromat
- Telefon 2 - integromat
- Telefon 3 - integromat
- Telefon 4 - integromat
- web - integromat
- Kontakt 2 - integromat
- Kontakt 3 - integromat
- Vstupní bod - integromat
- Referrer - integromat
- Vyhledávací dotaz - integromat
- Zobrazeno stránek - integromat
- Stráveno celkem vteřin - integromat
- Cesta 1 - integromat
- Stráveno vteřin 1 - integromat
- Zobrazeno stránek 1 - integromat
- Cesta 2 - integromat
- Stráveno vteřin 2 - integromat
- Zobrazeno stránek 2 - integromat
- Cesta 3 - integromat
- Stráveno vteřin 3 - integromat
- Zobrazeno stránek 3 - integromat
- Cesta 4 - integromat
- Stráveno vteřin 4 - integromat
- Zobrazeno stránek 4 - integromat
- Cesta 5 - integromat
- Stráveno vteřin 5 - integromat
- Zobrazeno stránek 5 - integromat
- PABC
- PH_ORD
- PHA
- PHAT
- PHBILL
- PHBU
- PHC
- PHCU
- PHD
- PHE
- PHE_Z
- PHEU
- PHG
- PHI
- PHI2P
- PHINV
- PHL_E
- PHL_S
- PHLU
- PHM_E
- PHM_E_DUO
- PHM_M
- PHM_M_DUO
- PHM_S
- PHMAE1
- PHN
- PHN_PRO
- PHNA
- PHNAHLD1
- PHNAHLDX
- PHNAHLP1
- PHO
- PHP
- PHPA
- PHRB
- PHREP
- PHRK
- PHROUT
- PHSK
- PHSRV
- PHT
- PHUNI
- PHX
- PHX_PRO
- PHXG
- PHXU
- PCH
- PPR
- PSM
- plusCollect
- Stráveno vteřin 1 - integromat číselné pole
- PHVALID
- PHREDIRECT
- PHPR
- PHPA_CAL
- PHN_PRO_DUO
- PHI2P_PRO
- PBON
- PHKON
- PHMA
- PHPI
- PHMA_CAL
- PHAGRI
- ID Pohoda - KS
- C66-A13-2
- C66-CRDRB
- C66-PGB
- C66-CRDPG
- C66-2-A9
- C66-A9-2
- C66-U
- C66-A11-2
- C66-A11
- C66-PRCH
- C66-B
- C66-A11-2U
- C66-RB
- C66-SP
- C66-PRCC
- C66-FP
- C66-CRD4B
- C66-HS
- C66-CRD
- C66-PP
- C66-USB
- C66-A13-2LR
- C66-PGB-OLD
- C66-PRCH-HS
- C66-CCCB
- C66-2
- C66-U-V1
- C66-A9
- C66-A11-2VM
- C66-C
- C66-WBC
- C66-PRC
- C66-BC
- C66-RH
- C66-P
- C66-MB
- C66-VC
- C61-A11-2
- C61-PGB
- C61-CRD
- C61-A9-2
- C61-RC
- C61-SP
- C61-HS
- C61-A11-2N
- C61-A13-2LR
- C61-A13-2
- C61-PGB-OLD
- C61-A11-2LR
- C61-A9-2N
- C61-A9-2LR
- C61-CRDMB
- C61-B
- C61-CCP
- C61-FP
- C61-CCN
- C61-2
- C61-A13-2N
- C61-A13-2LR2N
- C61-RCP
- C61-A9-2U
- C61-PG
- C61-2LR
- C61-CRDE
- C6000-CRD
- C6000-A10-2PG
- C6000-RC
- C6000-B
- C6000-A13-2PG
- C6000-A13-2
- C6000-BC
- C6000-A6-1PG
- C6000-2PG
- C6000-1PG
- C6000-FP
- C6000-A10-2
- C6000-A6-2PG
- C6000-A6-2
- C6000-2
- C6000-RH
- C6000-8B
- C6000-PG
- C6000-SP
- C6000-CCN
- C7x-AD
- C70-2
- C72-2
- C72-A11-2
- C72-CRDRB
- C7x-USB
- C72-2-P
- C72-CRD
- C72-B
- C7x-FP
- C72-2MR
- C72-A8-2MR
- C72-CCP
- C7x-SP
- C70T-A6-2
- C71-A11-2U
- C71-A11-U
- C71-A6
- C71-A6-1
- C71-CRD
- C72-A11-2MR
- C72-A11-2U
- C72-A11-U
- C72-A13-2
- C72-RC
- C7x-CCN
- C70-RB
- C71-2
- C72-A6-2U
- C72-A6-U
- C72-U
- C71-2U
- C71-B
- C72-2U
- C72-A6-2
- C70-A6-2
- C71-A8-2U
- C70-B
- C71-A11-2
- C71-A6-2
- C71-A8-2
- C70-CRD
- C71-U
- C71-A6-2U
- C71
- C71-RH
- C72-8-2MR
- C72-A13-2U
- C72-A13-U
- C72-PG
- C72-RH
- C75-2
- C72-A13-2MR
- C72-8-2
- C72-A8-2
- C71-A13-2U
- C71-1
- C71-CRDRB
- C71-RC
- C72-8-2U
- C72-1
- C72-A8-1
- C72-A6-2MR
- C71-A13-2
- C72-A6-2-P
- C71-A6-U
- ALN-9629-FW RW
- ALN-9630-FWRC
- ALN-9654-FW RW
- ALN-9713-W RW
- ALN-9840-WRC
- ALN-9840-WRW
- ALN-9940-WRW
- ALN-9954-WRW
- C4000-2UR
- C5-A13-2U
- C5-A13-2UN64
- CM1
- CM4
- CM710-4
- CM710-8
- CM8
- H86-Band-In-T
- H86-CS-NF
- H86-HP-6004
- H86-HRL-Po4026
- H86-HV-T-SMA
- H86-In-1515
- H86-In-1717
- H86-K-Li-Fe
- H86-Lanyard-BW
- H86-Lanyard-BW-FB
- H86-Lanyard-BW-PH
- H86-Lanyard-R
- H86-Lanyard-R-PH
- H86-Lanyards-R-PH
- H86-Lanyard-W
- H86-Lanyard-W-PH
- H86-Mo8K-Fe
- H86-MU
- H86-Ni-L
- H86-S91-T200
- H86-Sc-M2
- H86-Sc-M3
- H86SP-Mo8K-Fe-T-L
- H86SP-Mo8K-T-Fe-L
- 'H86SP-Prototyp: 1/02/22'
- 'H86SP-Prototyp: 2/02/22'
- H86T-MT-M4
- H86-TW-Fe
- H86U-MT-M3
- H86U-MT-M4
- H86-WBP-B
- H86-WBP-R
- H86-WBP-Sport-R
- H86-WL-9527
- H86-WL-9527-V2
- H86-WL-Fe
- H86-WL-IC
- H86-WL-K
- H86-WL-Slza
- H86-WL-TE
- H86-WL-TE-100x30
- H92(86)SP-Mo8K-Fe-L
- MR20
- P80-U-A7
- R1
- R2-2
- R3
- R5
- R6-2
- SR160
- SR160-BT
- U300-A11-4
- UR4
- UR4-12
- UR4-5
- UR4-9
- UR4-N
- UR4-N-1
- UR4-N-5
- UR4-SMA
- UR4-SMA-1
- UR4-SMA-5
- URA4-N-5
- URA8
- ZD6A142-30EFR2EZ
- C5-A13-2U-P
- PHM_E_FIRST
- PHN_START
- PHN_PROFI
- PHM_E_PRO
- PH_IMA
- PC
- PC_ADD
- PC_C61_ADD
- PC_C61_FIRST
- PC_C66_ADD
- PC_C66_FIRST
- PC_PRO
- PC_PRO_TERM
- PC_TERM
- PCM_TERM
- PCM_PRO
- PCM_PRO_TERM
- PCM
- PHM_PRO
api_base_url: https://app.smartemailing.cz
ping_status: ok
custom_field_count: 358
